version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            yarn build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: |
            yarn test
  lint:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: |
            yarn lint
  e2e:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build
          command: |
            yarn build
      - run:
          name: E2E
          command: |
            yarn e2e:headless

workflows:
  CI:
    jobs:
      - build
      - test
      - lint
      - e2e
        - requires:
            - build
