import type { NextPage } from "next";
import Head from "next/head";
import MainPage from "../layouts/main-page/MainPage";

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPage />
    </div>
  );
};

export default Index;
